# Generated by Django 4.2 on 2026-02-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_department_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='check_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.scansummary'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('SKIPPED', 'Skipped')], default='FAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
