# Generated by Django 4.2 on 2026-02-07 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_scanresult_check_id_alter_scanresult_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Account auto-disables at this date/time', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who last modified this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='Force user to change password on next login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_last_changed',
            field=models.DateTimeField(blank=True, help_text='Last password change timestamp for security scorecard', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login'), ('SCAN_UPLOADED', 'Scan Uploaded'), ('REPORT_VIEWED', 'Report Viewed'), ('REPORT_EXPORTED', 'Report Exported'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('POLICY_CREATED', 'Policy Created'), ('POLICY_UPDATED', 'Policy Updated'), ('MFA_ENABLED', 'MFA Enabled'), ('MFA_DISABLED', 'MFA Disabled'), ('PASSWORD_CHANGED', 'Password Changed'), ('API_KEY_CREATED', 'API Key Created'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('OTP_FAILED', 'OTP Verification Failed'), ('DEVICE_REGISTERED', 'Device Registered'), ('DEVICE_AUTHORIZED', 'Device Authorized'), ('DEVICE_REVOKED', 'Device Revoked'), ('SESSION_REVOKED', 'Session Revoked'), ('HEARTBEAT', 'Desktop Heartbeat'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated'), ('PASSWORD_RESET_FORCED', 'Password Reset Forced'), ('BULK_ACTION', 'Bulk Action'), ('ACCOUNT_EXPIRY_SET', 'Account Expiry Set')], max_length=50),
        ),
    ]
