# Generated by Django 4.2.28 on 2026-03-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_advanced_user_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='integrity_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of this entry chained to the previous entry.', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('TOTP', 'Authenticator App'), ('EMAIL', 'Email OTP')], default='EMAIL', help_text='Primary 2FA method. TOTP is preferred; EMAIL is fallback.', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login'), ('SCAN_UPLOADED', 'Scan Uploaded'), ('REPORT_VIEWED', 'Report Viewed'), ('REPORT_EXPORTED', 'Report Exported'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('POLICY_CREATED', 'Policy Created'), ('POLICY_UPDATED', 'Policy Updated'), ('MFA_ENABLED', 'MFA Enabled'), ('MFA_DISABLED', 'MFA Disabled'), ('PASSWORD_CHANGED', 'Password Changed'), ('API_KEY_CREATED', 'API Key Created'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('OTP_FAILED', 'OTP Verification Failed'), ('DEVICE_REGISTERED', 'Device Registered'), ('DEVICE_AUTHORIZED', 'Device Authorized'), ('DEVICE_REVOKED', 'Device Revoked'), ('SESSION_REVOKED', 'Session Revoked'), ('HEARTBEAT', 'Desktop Heartbeat'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated'), ('PASSWORD_RESET_FORCED', 'Password Reset Forced'), ('BULK_ACTION', 'Bulk Action'), ('ACCOUNT_EXPIRY_SET', 'Account Expiry Set'), ('SUDO_CONFIRMED', 'Sudo Mode Confirmed'), ('MFA_RESET_BY_ADMIN', 'MFA Reset By Admin'), ('TOTP_PROVISIONED', 'TOTP Provisioned')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp', 'id'], name='core_auditl_timesta_3238cd_idx'),
        ),
    ]
