# Generated by Django 6.0.3 on 2026-05-08 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_extension_request_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Authentication', 'Authentication'), ('Network', 'Network Security'), ('Data Protection', 'Data Protection'), ('Endpoint Security', 'Endpoint Security'), ('System', 'System Configuration'), ('Logging', 'Logging & Auditing'), ('Access Control', 'Access Control'), ('Encryption', 'Encryption'), ('Custom', 'Custom')], default='System', max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='MEDIUM', max_length=20)),
                ('framework', models.CharField(choices=[('CIS', 'CIS Benchmarks'), ('HIPAA', 'HIPAA'), ('SOC2', 'SOC 2'), ('PCI', 'PCI DSS'), ('ISO27001', 'ISO 27001'), ('NIST', 'NIST CSF'), ('CUSTOM', 'Custom')], default='CIS', max_length=20)),
                ('control_id', models.CharField(blank=True, help_text='Framework control reference (e.g., CIS 1.1.1, HIPAA §164.312)', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=20)),
                ('check_id', models.CharField(blank=True, help_text='Links to an AVAILABLE_CHECKS key in the desktop agent engine', max_length=100)),
                ('remediation_guidance', models.TextField(blank=True)),
                ('is_custom', models.BooleanField(default=False, help_text='True if created by the organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Null = global policy applicable to all organizations', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='core.organization')),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['category', 'severity', 'name'],
            },
        ),
    ]
